---
- hosts: localhost 
  connection: local
  become: true
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

  #Apache Configuration
    - name: Install LAMP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'openjdk-8-jdk' ]
    - name: Downloading tomcat
      get_url:
        url: http://apache-mirror.8birdsvideo.com/tomcat/tomcat-9/v9.0.31/bin/apache-tomcat-9.0.31.tar.gz
        dest: /tmp
    - name: Extracting tomcat
      unarchive:
              src: "/tmp/apache-tomcat-9.0.31.tar.gz"
              dest: "/tmp"
    - name: Running tomcat
      shell: /tmp/apache-tomcat-9.0.31/bin/startup.sh

